name: Flutter Web CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        dart-version: '3.3.4'
        # Ensure this is a version that includes Dart SDK 3.3.4

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./build
